### ISSUE TITLE
update 

### ISSUE THREAD

**Issue by paulsavo1** [claudioruiz/calendario-copa-america-2019#2]
hi i seen your reply but it is not fully updating it gives for eg Colombia 🇨🇴 v 2C

its no big deal just be nice if fully updated

thanks

**Comment by claudiorrrr** [comment]
Did you try to refresh it?

Keep in mind ideally you should be "subsribed" to the URL instead of downloading the file and manually upload it to your calendar, case of which it will not be automagically be updated ;)

I just re-subscribe to it and this is what I see:

![image](https://user-images.githubusercontent.com/390030/60212457-4b8e1b80-982f-11e9-9c91-790c21989689.png)

**Comment by paulsavo1** [comment]
updated now thanks
